server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    #    hibernate:
    #      ddl-auto: none
    #      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  sql:
    init:
      mode: never

  flyway:
    enabled: true

  kafka:
    template:
      default-topic: gateway.request
    consumer:
      group-id: taskManagerConsumer
      bootstrap-servers: localhost:9092

app-kafka:
  topicName: taskManager.request
  partitions: 1
  replicas: 1

#logging:
#  level:
#    ROOT: ERROR
